### PR TITLE
Extract docs to their own repo

### LINKED ISSUE #295: Extract docs to their own repo
The documentation is currently duplicated across ocfweb and ocfstatic. This means that the content of them has diverged between the two websites, with some people making PRs to add content to docs on ocfweb and some PRs to ocfstatic. I've already started a repo at https://github.com/Kalissaac/ocfdocs with the docs content and I think I've been able to merge everything together so far. On the branch `kian/extract-docs` I've done the work of using a git submodule to point the docs folder to that repo which will allow us to update docs in one place and have it take effect everywhere on the site.

### PR DESCRIPTION
**Pull request by Kalissaac**
This extracts all of our documentation to their own repo (currently at https://github.com/Kalissaac/ocfdocs but needs to be transferred to `ocf`). Useful since we can use this as the one source of truth for our documentation and then have all of the places where we consume the data be in sync with each other.

Fixes #295

### CODE REVIEW

**Review by ben9583 — COMMENTED** [review]
Should we have the ocfdocs repo at `ocf/ocfdocs`? Looks like here it's `Kalissaac/ocfdocs` for testing.

**Comment by Kalissaac** [comment]
> Should we have the ocfdocs repo at `ocf/ocfdocs`? Looks like here it's `Kalissaac/ocfdocs` for testing.

Yeah I'm hoping to transfer it to `ocf/docs`, but I need to talk to root staff to get it migrated

**Review by bdsomer — CHANGES_REQUESTED** [review]
I agree with @ben9583; once we get the docs moved to `ocf/ocfdocs` then we should move forward with this PR

**Comment by Kalissaac** [comment]
We're moving to a separate implementation of docs, so this is no longer needed

**Comment by fawaf** [comment]
there is a repo called https://github.com/ocf/docs still. does this move make that repo obsolete? if so, please to not have duplicate/confusing repos.

**Comment by Kalissaac** [comment]
I think that repo was from a test a few years ago, it's quite out of date compared to our current docs and lacks revision history. When we finalize on a solution for docs we'll probably use that repo as the new home for public-facing docs backed by Git.

**Pull request closed without merging**
