### PR TITLE
Discord link178

### PR DESCRIPTION
**Pull request by RonitNath**
I've put in a link to our discord with discord's official svg logo, however, I don't know how to actually make the image show up, and I want to go to sleep. Thoughts?

(This follows up on issue 178, hence the naming)

### CODE REVIEW

**Comment by RonitNath** [comment]
I have no idea why all of bentref's commits are there too, but mine's at the bottom

**Comment by RonitNath** [comment]
Hold on let me try this again

**Comment by RonitNath** [comment]
Wait actually does anyone have any ideas for how to fix this issue?

**Comment by PotatoParser** [comment]
I think you could delete this branch, checkout master, pull from master, make a new branch and check that branch out, make your changes, and then commit.

**Pull request closed without merging**
