### PR TITLE
fix meeting time/format

### LINKED ISSUE #244: Update info about meetings on homepage
Currently the staff meeting info on the homepage says the wrong date, and it doesn't say that the meetings are actually in person at the lab. This would be a good first issue for someone to change this!

### PR DESCRIPTION
**Pull request by ben9583**
Corrects the meeting time and format on the website homepage.

Fixes #244.

### CODE REVIEW

**Comment by ben9583** [comment]
Ideally, this should be done using some sort of API, but I'm not super familiar with how the setup should be; is there someway we can do this? I would be happy to try and get some of that stuff done.

**Review by bentref — APPROVED** [review]
Looks good to me! if you're interested in converting this to an API we can talk in more detail about that but I think we should merge this right now!

**Comment by bentref** [comment]
@ben9583 You can go ahead and merge this yourself since it's approved! Let me know if you have any questions

If you're here at Hack Day I don't think we've met yet-- I'm in a dark green button-down shirt on the side of the room closer to the green chairs :)

**Comment by ben9583** [comment]
Alright, will do, thanks for the review!

Btw yes I'm here lol, I'm in the grey t-shirt in the middle, closest to the tv on the right side.

**Pull request merged**
